spring.application.name=Spring

spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:postgresql://localhost:5432/spring
spring.datasource.username=nivin@2005
spring.datasource.password=nivin@2005

spring.data.redis.host = localhost
spring.data.redis.port = 6379
spring.data.redis.timeout = 5000

spring.kafka.bootdtrap-servers = 9092